required_variables_forecast_archive:
  - weather_code
  - temperature_2m_max
  - temperature_2m_min
  - temperature_2m_mean
  - apparent_temperature_max
  - apparent_temperature_min
  - apparent_temperature_mean
  - sunrise
  - sunset
  - daylight_duration
  - sunshine_duration
  - precipitation_sum
  - rain_sum
  - snowfall_sum
  - precipitation_hours
  - wind_speed_10m_max
  - wind_gusts_10m_max
  - wind_direction_10m_dominant
  - shortwave_radiation_sum
  - et0_fao_evapotranspiration

required_variables_air_conditions:
  - european_aqi
  - us_aqi
  - pm10
  - pm2_5
  - carbon_monoxide
  - nitrogen_dioxide
  - sulphur_dioxide
  - ozone
  - aerosol_optical_depth
  - dust
  - uv_index
  - uv_index_clear_sky
  - ammonia
  - alder_pollen
  - birch_pollen
  - grass_pollen
  - mugwort_pollen
  - olive_pollen
  - ragweed_pollen- 