CREATE TABLE air_quality_data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    city_name TEXT NOT NULL,
    latitude REAL NOT NULL,
    longitude REAL NOT NULL,
    timezone TEXT NOT NULL,
    date DATE,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    european_aqi REAL,
    us_aqi REAL,
    pm10 REAL,
    pm2_5 REAL,
    carbon_monoxide REAL,
    nitrogen_dioxide REAL,
    sulphur_dioxide REAL,
    ozone REAL,
    aerosol_optical_depth REAL,
    dust REAL,
    uv_index REAL,
    uv_index_clear_sky REAL,
    ammonia REAL,
    alder_pollen REAL,
    birch_pollen REAL,
    grass_pollen REAL,
    mugwort_pollen REAL,
    olive_pollen REAL,
    ragweed_pollen REAL
);
