-- Define weather data table schema
CREATE TABLE IF NOT EXISTS weather_replace (
    city TEXT,
    latitude REAL,
    longitude REAL,
    timezone TEXT,
    date DATE,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    temperature_2m_max REAL,
    temperature_2m_min REAL,
    apparent_temperature_max REAL,
    apparent_temperature_min REAL,
    precipitation_sum REAL,
    rain_sum REAL,
    showers_sum REAL,
    snowfall_sum REAL,
    precipitation_hours REAL,
    precipitation_probability_max REAL,
    precipitation_probability_min REAL,
    precipitation_probability_mean REAL,
    weather_code TEXT,
    sunrise TEXT,
    sunset TEXT,
    sunshine_duration REAL,
    daylight_duration REAL,
    wind_speed_10m_max REAL,
    wind_gusts_10m_max REAL,
    wind_direction_10m_dominant REAL,
    shortwave_radiation_sum REAL,
    et0_fao_evapotranspiration REAL,
    uv_index_max REAL,
    uv_index_clear_sky_max REAL,
    PRIMARY KEY (city, date)
);
